//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ass        ///bum        ///cok        ///cox        ///cum        ///fag        ///fuk        ///gay        ///nob        ///sex        ///wop        ///anal        ///anus        ///arse        ///boob        ///butt        ///cawk        ///cipa        ///clit        ///cock        ///coon        ///crap        ///cums        ///cunt        ///dago        ///damn        ///dick        ///dink        ///fags        ///feck        ///fuck        ///fuks        ///gook        ///heeb        ///homo        ///knob        ///orgy        ///piss        ///poop        ///porn        ///quim        ///shag        ///shit        ///slag        ///slut        ///smeg        ///spic        ///suck        ///tard        ///tits        ///turd        ///twat        ///wang        ///wank        ///arrse        ///asses        ///balls        ///bitch        ///boner        ///boobs        ///chinc        ///chink        ///choad        ///clits        ///cocks        ///coons        ///cunts        ///dicks        ///dildo        ///dinks        ///faggs        ///fagot        ///fanny        ///fecal        ///fucks        ///fuker        ///gaydo        ///horny        ///juggs        ///kooch        ///labia        ///nigga        ///penis        ///prick        ///pussy        ///semen        ///shite        ///shits        ///sluts        ///spick        ///sucks        ///titty        ///twats        ///vulva        ///wanky        ///whoar        ///w [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string swear_words {
            get {
                return ResourceManager.GetString("swear_words", resourceCulture);
            }
        }
    }
}
